spring:
  application:
    name: booking-platform
  config:
    import: optional:classpath:secrets.properties

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
#      must change !!! TODO
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
          fetch_size: 50
        order_inserts: true
        order_updates: true
    show-sql: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET:MyVerySecureJwtSecretKeyThatIsAtLeast32CharactersLongForHS256Algorithm}
  expiration: ${JWT_EXPIRATION:86400000}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    operations-sorter: method
#    tags-sorter: alpha
#  api-docs:
#    path: /v3/api-docs

logging:
  level:
    root: INFO
    com.platform: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
